# Generated by Django 3.1.4 on 2020-12-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_types', '0001_initial'),
        ('architectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='architecture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='architecture_types.architecturetype'),
        ),
    ]
