# Generated by Django 3.1.4 on 2020-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architectures', '0002_architecture_architecture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
